import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeSwitcher from '@/components/ui/ThemeSwitcher/ThemeSwitcher';
import { LangType } from '@/lib/types/LangType';
import { getDictionary, langs } from '@/lib/utils/getDictionary';
import LangSwitcher from '@/components/ui/LangSwitcher/LangSwitcher';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LangType }>;
}>) {
  const lang = (await params).lang;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang || 'en'}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeSwitcher themes={dict.theme} />
        <LangSwitcher currentLang={lang} langs={langs} />
        {children}
      </body>
    </html>
  );
}
