import type { Metadata } from 'next';

import '@/styles/globals.css';
import LangSwitcher from '@/components/ui/LangSwitcher/LangSwitcher';
import ThemeSwitcher from '@/components/ui/ThemeSwitcher/ThemeSwitcher';
import { LangType } from '@/lib/types/LangType';
import { getDictionary, langs } from '@/lib/utils/getDictionary';
import { roboto } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LangType }>;
}>) {
  const lang = (await params).lang;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang || 'en'}>
      <body
        className={`font-roboto ${roboto.variable} font-normal antialiased`}
      >
        <ThemeSwitcher themes={dict.theme} />
        <LangSwitcher currentLang={lang} langs={langs} />
        {children}
      </body>
    </html>
  );
}
