import type { Metadata } from 'next';

import '@/styles/globals.css';
import LangSwitcher from '@/components/features/LangSwitcher/LangSwitcher';
import Socials from '@/components/features/Socials/Socials';
import ThemeSwitcher from '@/components/features/ThemeSwitcher/ThemeSwitcher';
import TopNavigation from '@/components/features/TopNavigation/TopNavigation';
import Header from '@/components/layout/Header/Header';
import { LangType } from '@/lib/types/LangType';
import { getDictionary, langs } from '@/lib/utils/getDictionary';
import { roboto } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: LangType }>;
}>) {
  const lang = (await params).lang;
  const dict = await getDictionary(lang);

  return (
    <html lang={lang || 'en'}>
      <body
        className={`font-roboto ${roboto.variable} font-normal antialiased`}
      >
        <Header>
          <TopNavigation linkLabels={dict.nav.links} />
          <ThemeSwitcher themes={dict.theme} />
          <LangSwitcher currentLang={lang} langs={langs} />
          <Socials />
        </Header>
        <main className="container mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
